<?php
if (session_status() === PHP_SESSION_NONE) {
    session_start();
}

// 1. Enforce Authentication & Role Security
if (!isset($_SESSION['user_id']) || $_SESSION['role'] !== 'owner') {
    header("Location: ../default-browser/index.php?error=unauthorized");
    exit();
}

// 2. Include database connection file
require_once 'database-connection.php';

// 3. Process form request only on POST submission
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    
    $owner_id      = $_SESSION['user_id'];
    $property_name = trim($_POST['property_name'] ?? '');
    $property_type = trim($_POST['property_type'] ?? '');
    $description   = trim($_POST['description'] ?? '');
    $address       = trim($_POST['address'] ?? '');
    
    // Capture and validate optional geometric coordinates
    $latitude  = filter_input(INPUT_POST, 'latitude', FILTER_VALIDATE_FLOAT);
    $longitude = filter_input(INPUT_POST, 'longitude', FILTER_VALIDATE_FLOAT);
    
    // Treat invalid or empty inputs for coordinates as NULL values for the DB
    $latitude  = ($latitude !== false && $latitude !== null) ? $latitude : null;
    $longitude = ($longitude !== false && $longitude !== null) ? $longitude : null;

    // 4. Base field validation rules
    if (empty($property_name) || empty($property_type) || empty($address)) {
        header("Location: ../owner/o-property.php?error=missing_required_fields");
        exit();
    }

    // 5. Begin a database transaction to ensure both tables save accurately 
    $conn->begin_transaction();

    try {
        // Query matching your schema: property_id, owner_id, property_name, property_type, description, address, latitude, longitude, created_at
        $property_query = "INSERT INTO properties (owner_id, property_name, property_type, description, address, latitude, longitude) 
                           VALUES (?, ?, ?, ?, ?, ?, ?)";
        
        $stmt = $conn->prepare($property_query);
        $stmt->bind_param("issssdd", $owner_id, $property_name, $property_type, $description, $address, $latitude, $longitude);
        
        if (!$stmt->execute()) {
            throw new Exception("Property baseline registry failed.");
        }
        
        // Grab the freshly auto-incremented property_id generated by MySQL
        $property_id = $conn->insert_id;
        $stmt->close();

        // 6. Handle Multi-Image Upload File Array
        if (isset($_FILES['property_images']) && !empty($_FILES['property_images']['name'][0])) {
            
            $file_count = count($_FILES['property_images']['name']);

            // Enforce constraints on the server layer
            if ($file_count < 1 || $file_count > 3) {
                throw new Exception("Property registry requires a minimum of 1 and a maximum of 3 images.");
            }

            $target_dir = "../../uploads/property_photos/";
            if (!file_exists($target_dir)) {
                mkdir($target_dir, 0755, true);
            }

            $allowed_extensions = ['jpg', 'jpeg', 'png', 'webp'];
            $image_query = "INSERT INTO property_images (property_id, image_url) VALUES (?, ?)";
            $img_stmt = $conn->prepare($image_query);

            for ($i = 0; $i < $file_count; $i++) {
                if ($_FILES['property_images']['error'][$i] !== UPLOAD_ERR_OK) {
                    continue; 
                }

                $file_name = $_FILES['property_images']['name'][$i];
                $file_tmp  = $_FILES['property_images']['tmp_name'][$i];
                $file_ext  = strtolower(pathinfo($file_name, PATHINFO_EXTENSION));

                if (in_array($file_ext, $allowed_extensions)) {
                    $new_file_name = "prop_" . $property_id . "_" . uniqid() . "." . $file_ext;
                    $target_file_path = $target_dir . $new_file_name;

                    if (move_uploaded_file($file_tmp, $target_file_path)) {
                        $db_save_path = "uploads/property_photos/" . $new_file_name;
                        $img_stmt->bind_param("is", $property_id, $db_save_path);
                        if (!$img_stmt->execute()) {
                            throw new Exception("Image entry reference tracking save error.");
                        }
                    }
                }
            }
            $img_stmt->close();
        } else {
            // Throws an error if no file was uploaded on registration
            throw new Exception("You must upload at least 1 image for your property.");
        }

        // Commit all changes to the database simultaneously if all steps pass
        $conn->commit();
        header("Location: ../owner/o-property.php");
        exit();

    } catch (Exception $e) {
        // Rollback operations back to initial state if any error occurs
        $conn->rollback();
        header("Location: ../owner/o-property.php?error=registration_aborted&msg=" . urlencode($e->getMessage()));
        exit();
    }

} else {
    header("Location: ../owner/o-property.php");
    exit();
}
